[package]
name = "ffuu-markdown"
version = "0.1.0"
authors = ["Kevin Sullivan <kevin@sull.vn>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.8"
anyhow = "1.0"

[dependencies.async-std]
version = "1.9"
features = ["attributes"]